"""Build v3 without modifying the immutable v1 artifact or released Index."""
import os
import tempfile
from pathlib import Path

from ..build import code_receipts, load_partition, verify as verify_v1
from ..common import SPLITS, TRACKS, digest, file_hash, read_json, rows, summary, write_json, write_rows
from . import audit, cic, endpoint, language, network, network_rules, policy, shortcuts, workplace
from .common import VERSION, REVISION, carry


def original_rows(parent):
    verify_v1(parent)
    return [r for split in SPLITS for r in load_partition(parent, split)]


def code_pins():
    root = Path(__file__).parent
    files = [*root.glob("*.py"), *root.glob("vendor/*")]
    return {str(p.relative_to(root)): file_hash(p) for p in sorted(files)}


def verify(directory):
    directory = Path(directory)
    m = read_json(directory / "manifest.json")
    if m["version"] != VERSION:
        raise ValueError("Not a v3 dataset")
    for path, pin in m["files"].items():
        p = directory / path
        if file_hash(p) != pin["sha256"] or p.stat().st_size != pin["bytes"]:
            raise ValueError(f"Frozen v3 file changed: {path}")
    values = [r for s in SPLITS for r in load_partition(directory, s)]
    parent = Path(m["parent"]["path"])
    if not parent.is_absolute():
        candidates = [directory.parent / parent, directory.parent.parent / parent]
        parent = next((p for p in candidates if (p / "manifest.json").exists()), candidates[0])
    originals = original_rows(parent)
    if file_hash(parent / "manifest.json") != m["parent"]["manifest_sha256"]:
        raise ValueError("Parent release changed")
    p = read_json(directory / "reports/protection.json")
    p = {k: set(v) if k != "receipts" else v for k, v in p.items()}
    checks = audit.validate(values, originals, p)
    if checks != read_json(directory / "reports/audit.json")["structural"]:
        raise ValueError("Frozen v3 audit no longer matches rows")
    return {"version": VERSION, "cases": len(values), "questions": sum(len(r["questions"]) for r in values),
            "files_verified": len(m["files"]), "counts": m["counts"], "test_predictions_performed": False}


def review_packets(staging, values):
    required = [r for r in values if r["family"] == "authorization_policy" or
                r["family"] == "endpoint_investigation" and not r["metadata"]["diagnostic_only"]]
    # Each reviewer answers the entire same packet independently. Neither gold
    # nor pair identity nor parser verdict is part of the packet.
    source_fields = {"path", "sha256", "native_refs", "source_text_sha256", "source_line", "source_line_sha256", "byte_start", "byte_end"}
    blind = [{"id": r["id"], "track": r["family"], "state": r["state"], "questions": r["questions"],
              "source_evidence": {k: v for k, v in r["provenance"].items() if k in source_fields}}
             for r in sorted(required, key=lambda r: digest(["blind-review", r["id"]]))]
    # Provenance of policy intervention includes edits, not the generated answer.
    write_rows(staging / "review/blinded-cases.jsonl.gz", blind)
    write_rows(staging / "review/answer-template.jsonl", [{"id": r["id"], "reviewer_id": "",
        "answers": {q: "" for q in r["questions"]}, "confidence": "", "issue": ""} for r in blind])
    write_json(staging / "review/requirements.json", {"reviewers_required": 2, "required_case_ids": [r["id"] for r in blind],
        "scope": "Every policy and non-diagnostic endpoint case, across all three partitions.",
        "blinding": "No gold answers, generated match identifiers or parser verdicts. Reviewers answer independently before adjudication.",
        "gate": "Every reviewer must identify their security expertise, complete every required answer, and disclose conflicts. "
                "Any disagreement with the frozen answer must be adjudicated before certification; label fixes require a new immutable edition."})
    write_json(staging / "review/profile-template.json", {"reviewer_id": "", "name": "", "security_expertise": "",
               "conflicts": "", "independent_review": False})
    (staging / "review/README.md").write_text("Review blinded-cases.jsonl.gz independently. Copy answer-template.jsonl to your own file and fill semantic choice keys. "
        "Check authorization scope, actual response dependency, destination context, and scoped grants. For endpoint, check native host/GUID/time links, "
        "missing evidence and minimal supporting event references. Explain every issue. No model score is provided. "
        "Return the completed JSONL and a reviewer profile with reviewer_id, name, security_expertise and conflicts. "
        "The review certificate is generated by the review command, never by the benchmark builder.\n")
    return len(required)


def build(parent, collection, sev_root, typescript, out, work, log=print):
    parent, collection, sev_root, typescript, out, work = [Path(x).resolve() for x in (parent, collection, sev_root, typescript, out, work)]
    if out.exists():
        raise FileExistsError("Frozen destination exists; choose a new edition")
    originals = original_rows(parent)
    work.mkdir(parents=True, exist_ok=True)
    pins = code_pins()
    phases = {"authorization_policy": lambda: policy.build([r for r in originals if r["family"] == "authorization_policy"], sev_root, typescript, log),
              "endpoint_investigation": lambda: endpoint.build([r for r in originals if r["family"] == "endpoint_investigation"],
                  read_json(parent / "reports/endpoint_investigation.json"), collection, log=log),
              "network_defense": lambda: network.build([r for r in originals if r["family"] == "network_defense"], collection, log=log)}
    values = [carry(r) for r in originals if r["family"] == "incident_triage"]
    reports = {"incident_triage": read_json(parent / "reports/incident_triage.json")}
    # The phase stamps cover the precise phase code, parent manifest and source
    # collection directory. They allow interrupted construction to resume.
    for track, builder in phases.items():
        phase = {"authorization_policy": "policy", "endpoint_investigation": "endpoint", "network_defense": "network"}[track]
        module_root = Path(__file__).parent
        dependencies = [module_root / (phase + ".py"), module_root / "common.py", module_root.parent / (phase + ".py"),
                        module_root.parent / "common.py", module_root.parent / "build.py", module_root.parent.parent / "suite/io.py"]
        if phase == "policy":
            dependencies += list((module_root / "vendor").glob("*")) + [typescript]
        stamp = digest({"parent": file_hash(parent / "manifest.json"), "phase_code": {str(p): file_hash(p) for p in dependencies}, "collection": str(collection)})
        data, report, cache = work / f"{track}.jsonl.gz", work / f"{track}.json", work / f"{track}.cache.json"
        if cache.exists() and data.exists() and report.exists() and read_json(cache) == {"stamp": stamp, "data": file_hash(data), "report": file_hash(report)}:
            selected, info = list(rows(data)), read_json(report)
            log(f"Verified v3 phase cache: {track}")
        else:
            selected, info = builder()
            write_rows(data, selected)
            write_json(report, info)
            write_json(cache, {"stamp": stamp, "data": file_hash(data), "report": file_hash(report)})
        values.extend(selected)
        reports[track] = info
    rule_rows, rule_report = network_rules.build(collection, read_json(parent / "reports/endpoint_investigation.json"),
        {r["metadata"]["split_group"]: r["split"] for r in values if r["family"] == "endpoint_investigation"})
    values.extend(rule_rows)
    reports["network_boundary_rules"] = rule_report
    workplace_rows, reports["workplace_policy"] = workplace.build([r for r in originals if r["family"] == "authorization_policy"])
    values.extend(workplace_rows)
    cic_rows, reports["network_publisher_transfer"] = cic.build(collection, log=log)
    values.extend(cic_rows)
    values = [language.normalize(r) for r in values]
    reports["language"] = language.audit(values)
    if reports["language"]["flagged_authored_phrases"]:
        raise ValueError("Unresolved authored wording flagged by language audit")
    values.sort(key=lambda r: (r["family"], digest(["v3-order", r["id"]])))
    exported = read_json(parent / "reports/protection.json")
    protected = {k: set(v) if k != "receipts" else v for k, v in exported.items()}
    structural = audit.validate(values, originals, protected)
    reports["shortcuts"] = shortcuts.audit(values)
    source_replay = audit.replay(values, originals, reports, collection, log)
    if pins != code_pins():
        raise ValueError("Builder code changed during construction; resume against a stable code snapshot")
    out.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".esdb-v3-build-", dir=out.parent) as temporary:
        staging = Path(temporary) / VERSION
        staging.mkdir()
        for split in SPLITS:
            partition = [r for r in values if r["split"] == split]
            write_rows(staging / f"inputs/{split}.jsonl.gz", [{k: r[k] for k in ("id", "family", "split", "state", "questions", "_evaluation")} for r in partition])
            write_rows(staging / f"labels/{split}.jsonl.gz", [{k: r[k] for k in ("id", "expected", "metadata", "provenance")} for r in partition])
        write_json(staging / "reports/protection.json", exported)
        write_json(staging / "reports/audit.json", {"structural": structural, "source_replay": source_replay})
        for track, report in reports.items():
            write_json(staging / f"reports/{track}.json", report)
        review_count = review_packets(staging, values)
        (staging / "README.md").write_text("# Enterprise Security Decision Benchmark v0.3\n\n"
            "Four separate tracks, with field extraction excluded from endpoint ranking and source datasets separated in network reporting. "
            "Policy variants are controlled authored interventions; GUIDE carries complete native real incidents. "
            "Independent security review is pending. No final test inference is admitted before the review certificate and frozen protocol.\n\n"
            "See ../../docs/cyber-v0.3.md. Inputs contain no gold; labels contain source provenance and answer keys. Source terms apply; "
            "recovered program reuse terms remain unresolved. This is a local research build, not a public release grant.\n")
        files = {str(p.relative_to(staging)): {"sha256": file_hash(p), "bytes": p.stat().st_size} for p in sorted(staging.rglob("*")) if p.is_file()}
        write_json(staging / "manifest.json", {"version": VERSION, "created_date": "2026-10-04", "status": "source-replayed; independent review pending",
            "parent": {"path": parent.name if parent.parent == out.parent else str(parent), "manifest_sha256": file_hash(parent / "manifest.json")},
            "files": files, "builder_sha256": pins, "inherited_builder_sha256": code_receipts(), "counts": structural["counts"],
            "partitions": structural["partitions"], "model": {"repo": "macmacmacmac/Sev-4B", "revision": REVISION},
            "review_cases": review_count, "test_policy": "Independent reviewer certification and immutable protocol required. One recorded final test execution; no repeated test selection.",
            "limitations": ["Source-program interventions are authored, not additional real incidents.", "Lab network labels are not enterprise field prevalence.",
                            "CTU/IoT share a lab. CSE-CIC-IDS2018 adds one independent lab campaign in the frozen test; related days are not independent incidents. Splunk rule labels are authored.",
                            "Public-source pretraining contamination is unknown. Known local Sev train/calibration/development overlap is excluded.",
                            "GUIDE predicts retrospective provider grades, not end-to-end online detection.", "Independent human security review remains pending."]})
        verify(staging)
        os.rename(staging, out)
    return verify(out)
